/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/0c6d825e-623f-4713-8dc3-3ac4aa949e5e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  int distancia;
  bool alarma1;
  bool led2;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const int Trigger = 27;   
const int Echo = 26;   

#define verde 12
#define rojo 13
#define amarillo 14
#define alarma 25

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  pinMode(Trigger, OUTPUT); 
  pinMode(Echo, INPUT);  
  pinMode(verde, OUTPUT);
  pinMode(rojo, OUTPUT);
  pinMode(amarillo, OUTPUT);
  pinMode(alarma, OUTPUT);
  
  digitalWrite(Trigger, LOW);
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  long t; 
  long d;

  digitalWrite(Trigger, HIGH);
  delayMicroseconds(10);
  digitalWrite(Trigger, LOW);
  
  t = pulseIn(Echo, HIGH); 
  d = t / 59;             
  distancia = (int)d;
  Serial.print("Distancia: ");
  Serial.print(d);      
  
  if (d > 25) {
    digitalWrite(verde, 1);
    digitalWrite(rojo, 0);
    digitalWrite(amarillo, 0);
    digitalWrite(alarma, 0);
    alarma1 = false;
  }
  if (d > 10 && d < 25) {
    digitalWrite(amarillo, 1);
    digitalWrite(rojo, 0);
    digitalWrite(verde, 0);
    digitalWrite(alarma, 0);
    alarma1 = false;
  }
  if (d <= 10) {
    digitalWrite(rojo, 1);
    digitalWrite(amarillo, 0);
    digitalWrite(verde, 0);
    digitalWrite(alarma, 1);
    alarma1 = true;
  }
  Serial.print("cm");
  Serial.println();
}
